###############################################################################
#  Site identity
###############################################################################
title        : "Rodgers Meroka Osumo"
tagline      : "Data Scientist & AI Strategist"
description  : "My portfolio & blog — building AI and data solutions for real-world impact."
locale       : "en"

# ── Where the site will live ──
url      : "https://rodgers-osumo.github.io"
baseurl  : "/portfolio"                 # "" if the repo itself is <username>.github.io

###############################################################################
#  Theme & plugins
###############################################################################
theme: "minimal-mistakes-jekyll"        # using the gem, not remote_theme

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

###############################################################################
#  Author block
###############################################################################
author:
  name     : "Rodgers Osumo"
  avatar   : "/assets/img/avatar.jpg"
  location : "Nairobi, Kenya"
  links:
    - label: "GitHub"
      icon : "fab fa-github"
      url  : "https://github.com/rodgersmerokaosumo"
    - label: "LinkedIn"
      icon : "fab fa-linkedin"
      url  : "https://www.linkedin.com/in/rodgers-osumo"

###############################################################################
#  Analytics (optional)

###############################################################################
#  Build settings
###############################################################################
markdown    : kramdown
highlighter : rouge
future      : true
