###############################################################################
#  Site identity
###############################################################################
title        : "Rodgers Meroka Osumo"
tagline      : "Data Scientist & AI Strategist"
description  : "My portfolio & blog — building AI and data solutions for real-world impact."
locale       : "en"

# ── Where the site will live ──
url      : "https://rodgersmerokaosumo.github.io"
baseurl  : "/portfolio"   # "" if this is a user site

###############################################################################
#  Theme & plugins
###############################################################################
theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate   # ← add the pagination plugin

###############################################################################
#  Pagination
###############################################################################
paginate: 5                     # posts per page
paginate_path: "/blog/page:num/"  # where extra pages live

###############################################################################
#  Author block
###############################################################################
author:
  name     : "Rodgers Osumo"
  avatar   : "/assets/img/avatar.jpeg"
  location : "Nairobi, Kenya"
  links:
    - label: "GitHub"
      icon : "fab fa-github"
      url  : "https://github.com/rodgersmerokaosumo"
    - label: "LinkedIn"
      icon : "fab fa-linkedin"
      url  : "https://www.linkedin.com/in/rodgers-osumo"

###############################################################################
#  Analytics (optional)
###############################################################################
# google_analytics: "G-XXXXXXXXXX"

###############################################################################
#  Build settings
###############################################################################
markdown    : kramdown
highlighter : rouge
future      : true


sass:
  style: compressed

# Tell Jekyll (and the theme) to also compile your custom.scss
defaults:
  - scope:
      path: ""            # all files
      type: "assets"
    values:
      css: ["assets/css/custom.scss"]

