###############################################################################
# Site identity
###############################################################################
title:       "Rodgers Meroka Osumo"
tagline:     "Data Scientist & AI Strategist"
description: "My portfolio & blog — building AI and data solutions for real-world impact."
locale:      "en"

# ── Where the site will live ──
url:     "https://rodgersmerokaosumo.github.io"
baseurl: "/portfolio"   # "" if repo is <username>.github.io

###############################################################################
# Theme & plugins
###############################################################################
theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Ensure Jekyll processes your custom stylesheet
include:
  - assets/css/main.scss

###############################################################################
# Build settings
###############################################################################
markdown:    kramdown
highlighter: rouge
future:      true
