title: "Rodgers Meroka Osumo"
tagline: "Data Scientist & AI Strategist"
url: "https://rodgersmerokaosumo.github.io"
baseurl: "/portfolio"       # keep empty
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

