###############################################################################
# Site identity
###############################################################################
title:       "Rodgers Meroka Osumo"
tagline:     "Data Scientist & AI Strategist"
description: "My portfolio & blog — building AI and data solutions for real-world impact."
locale:      "en"

# ── Where the site will live ──
url:     "https://rodgersmerokaosumo.github.io"
baseurl: "/portfolio"   # "" if repo is <username>.github.io
timezone: "Africa/Nairobi"

###############################################################################
# Theme & plugins
###############################################################################
theme: "jekyll-theme-journal-clone"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Ensure Jekyll processes your custom stylesheet
include:
  - assets/css/main.scss


###############################################################################
# Pagination settings
###############################################################################

pagination:                       # global settings for paginate-v2
  enabled: true                   # turn it on
  collection: posts               # paginate your posts
  per_page: 5                     # 5 posts per page
  permalink: "/blog/page/:num/"   # URL pattern for page 2+
  first_page_url: "/blog/"        # your blog’s main page


###############################################################################
# Build settings
###############################################################################
markdown:    kramdown
highlighter: rouge
future:      true

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

###############################################################################
# Layout defaults
###############################################################################
defaults:
  -
    scope:
      path: ""          
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""          
      type: "pages"
    values:
      layout: "page"

###############################################################################
# Navigation (header links)
###############################################################################
nav:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

###############################################################################
# Author & Social (for footer or bio includes)
###############################################################################
author:
  name: "Rodgers Meroka Osumo"
  avatar: "/assets/img/avatar.jpg"

social_links:
  twitter: your_twitter_handle
  github: rodgersmerokaosumo
  linkedin: your_linkedin_username

# Disqus comments
disqus:
  shortname: portfolio-iuncitmsgs


###############################################################################
# Google Analytics (optional)
###############################################################################
google_analytics: G-XSTELV0HPS

